In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/raw/ads_campaign_data.csv')
df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  object
 1   Campaign_Type     55555 non-null  object
 2   Target_Audience   55555 non-null  object
 3   Duration          55555 non-null  int64
 4   Channel_Used      55555 non-null  object
 5   Impressions       55555 non-null  int64
 6   Clicks            55555 non-null  int64
 7   Leads             55555 non-null  int64
 8   Conversions       55555 non-null  int64
 9   Revenue           55555 non-null  int64
 10  Acquisition_Cost  55555 non-null  float64
 11  ROI               55555 non-null  float64
 12  Language          55555 non-null  object
 13  Engagement_Score  55555 non-null  float64
 14  Customer_Segment  55555 non-null  object
 15  Date              55555 non-null  object
dtypes: float64(3), int64(6), object(7)
memory usage: 6.8+ MB

In [4]:
# using first 20k as train and next 5k as test
df_train = df[:20000]
df_test = df[20000:25000]

In [5]:
df_train.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [6]:
df_test.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
20000,NY-CMP-21000,Influencer,Working Women,12,Email,92643,6867,2602,973,575043,219.37,1.69,Tamil,11.27,Youth,08-08-2024
20001,NY-CMP-21001,Email,Working Women,6,"Email, YouTube, Instagram",32426,944,525,417,145533,662.19,-0.47,Tamil,5.82,Youth,21-12-2024
20002,NY-CMP-21002,SEO,Working Women,14,"Google, WhatsApp, Email",73879,8676,3483,1679,1198806,157.93,3.52,Tamil,18.73,Youth,30-05-2025
20003,NY-CMP-21003,Paid Ads,Tier 2 City Customers,7,"Email, Instagram",42527,3686,1502,488,384544,477.52,0.65,Hindi,13.35,College Students,16-04-2025
20004,NY-CMP-21004,Paid Ads,Tier 2 City Customers,18,"WhatsApp, Facebook",33467,2507,1472,923,457808,164.47,2.02,Tamil,14.65,Premium Shoppers,28-03-2025